### ISSUE TITLE
Style Footer UI [WEB-845]

### ISSUE THREAD

**Issue by xgambitox** [yearn/yearn-finance-v3#366]
**Elevator Pitch**
Style Footer Links and Icons 

**Customer Value**
Better UI design

**Definition of Done**
- Change provided logos on footer and add missing ones.
- Center elements in mobile view and fit nicely in rows
- Use available theme colors to set default lighter contrast, and darker color when on hover.

**Design Approach**
Add provided assets (Remove `fill` color from svg) and remove old ones.
Refactor `client/components/app/Footer` component as needed.

**Additional Context**
Should look like:
[Download Icons](https://gateway.pinata.cloud/ipfs/QmU4rfAprz8tfJgvYELcFGMcyaiHTdCUjoTRMofJ877n81)
![image](https://user-images.githubusercontent.com/18649057/141538196-2cda9a18-48a0-4aec-98da-6c6f15f75c7a.png)
On hover reference:
![image](https://user-images.githubusercontent.com/18649057/141538745-cc45fd6a-9cdf-4307-b580-2c9bdd18b431.png)

**Comment by yusiflinurlan** [comment]
@xgambitox Hello! Assign this to me, please

**Comment by parseb** [comment]
@yusiflinurlan done? status?

**Comment by zannis** [comment]
Posted a PR for this one #405.
