### ISSUE TITLE
NFT Owner Access [WEB-1025]

### ISSUE THREAD

**Issue by xgambitox** [yearn/yearn-finance-v3#373]
**Elevator Pitch**
Yearn NFT owners might have special access to features

**Customer Value**
Community can enjoy personalized custom features

**Definition of Done**
- NFT balances are fetched for current selected address and stored in redux state
- Woofy NFT balance is available in state
- Blue Pill NFT balance is available in state
- State clears on wallet disconnect 

**Design Approach**
- Add `getNftBalance(address)` to `UserService.ts` that fetches both Woofy and Blue Pill NFT balance.
- Add new `user` module in redux store, with an `nft` object to handle key-value pairs for each NFT and balance.
- Create `selectUserWoofyBalance` and `selectUserBluePillBalance` selectors
- Add an effect hook on Layout container to execute actions on wallet change event.

**Additional Context**
[Woofy and The Blue Pill NFTs](https://galaxy.eco/yearn/)

**Comment by TacosTonight** [comment]
@xgambitox Hi can I be assigned this issue?
