### ISSUE TITLE
yvBOOST withdraw amount is incorrect in withdraw modal

### ISSUE THREAD

**Issue by masha256** [yearn/yearn-finance-v3#399]
**Describe the bug**
In the new v3 UI, when withdrawing yvBOOST, the UI shows the vault share amount, not the claimable yveCRV equivalent amount. 

The v2 UI works correctly.

**To Reproduce**
1. Go to Labs
2. Click on withdraw of yvBOOST
3. Click "MAX" in "From Vault"
4. See that the "To Wallet" amount in the UI does not match the amount in the Labs summary list.

**Comment by gotzenx** [comment]
Fixed on: https://github.com/yearn/yearn-finance-v3/pull/442
