### ISSUE TITLE
Vault deposits on the Fantom Opera network do not show on vaults overview page unless clicked on first

### ISSUE THREAD

**Issue by kx9x** [yearn/yearn-finance-v3#417]
**Describe the bug**
When I connect to yearn.finance on Fantom Opera and go to the https://yearn.finance/#/vaults page, I can see a value for my holdings, but I don't see a list of my deposits.

If I click into the vaults I know that I have deposited in and then go back to the previous page, then the vault will show.

For example if I go to https://yearn.finance/#/vault/0x0A0b23D9786963DE69CB2447dC125c49929419d8 for the MIM vault and then back to https://yearn.finance/#/vaults, I will now see a deposits section:
![image](https://user-images.githubusercontent.com/7820952/147804750-482af560-3c16-40ca-96c0-064d7a1171eb.png)

**To Reproduce**
1. Deposit into a vault such as the MIM vault on yearn.finance using the fantom network
2. Click on vaults
3. Notice that you don't have a deposit section showing your deposit.
4. Click the MIM vault to go to its detail pages.
5. Hit "back to previous page" and notice you can now see your deposit in the MIM vault.

**Expected behavior**
My MIM vault deposits should always show on the vaults page.

**Screenshots**

**Environment Information**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Edge
 - Version 98.0.1100.3 (Official build) dev (64-bit)

**Additional context**
I also discussed this in the YFI Web telegram chat

**Comment by FoxTheSin** [comment]
Fixed by adapting/deploying curve calculations contract for ftm https://ftmscan.com/address/0x0b53e9df372e72d8fdcdbedfbb56059957a37128#code
