### ISSUE TITLE
Bug in Network selection (top right of home page)

### ISSUE THREAD

**Issue by Nicolascrd** [yearn/yearn-finance-v3#422]
**Describe the bug**
This happened when I tried to connect to my fantom wallet and then change the network to ethereum using the dropdown button on the top right of the page. The network just wouldn't change to ethereum.
There is an error in the logs : o.wallet.provider.request is not a function

**To Reproduce**
1. Go to https://yearn.finance/#/home
2. Click on 'Ethereum' to open the dropdown button then select fandom
3. Do as if you wanted to connect a wallet ( I did that with ledger ) but do not connect anything. Then cancel (dismiss button).
4. Try to select Ethereum back in dropdown button
5. You should notice the error

**Expected behavior**
You should be able to select Ethereum.

**Screenshots**
The dropdown button I am referencing is this : 
![image](https://user-images.githubusercontent.com/72993859/148042484-c47763c8-34be-4976-87b8-00c09dec7d04.png)

The console error I get is this :
![image](https://user-images.githubusercontent.com/72993859/148042645-c5f19973-6add-465f-9c5b-604310be019b.png)

**Environment Information**
 - OS: Ubuntu 20.04.3 LTS
 - Browser Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by FoxTheSin** [comment]
additional testing info:
if you connect wallet before network change, does not error.

also not just for ledger wallet, any wallet brings up different errors when you switch network then try and connect

**Comment by xgambitox** [comment]
Tried to reproduce right now but probably fixed with https://github.com/yearn/yearn-finance-v3/pull/559

@FoxTheSin can you confirm?

**Comment by FoxTheSin** [comment]
believe is resolved. will open again if rediscovered
