### ISSUE TITLE
Improve simulations user facing errors

### ISSUE THREAD

**Issue by FiboApe** [yearn/yearn-finance-v3#440]
**Elevator Pitch**
Errors while simulating deposit are very generic and does not give users clear information about what went wrong. This also makes it harder for debugging when a user reports a bug (see image attached)
![photo_2022-01-13 16 07 16](https://user-images.githubusercontent.com/94012134/149398054-798d1859-eeea-4ee7-af2d-a68728ecb476.jpeg)

**Customer Value**
This will allow the users to have better information about why a simulation might be failing, even notifying them if some error coudl be fixed by them directly, so it could reduce also the number of support requests that we get.

**Definition of Done**
- [ ] Handle custom error types and codes for simulation coming from sdk
- [ ] Show specific error regarding each error code on a simulation fail

**Design Approach**
The idea is to have the errors thrown by the SDK to have the following structure: 
```
{
  error_code: string, // The specific error code that happened
  error_type: string, // Where the error originated from (zapper, contracts, tenderly, sdk own error, etc)
  message: string // Default message to show to the user in case it is not being handled
  data: any, // metadata that might come with the error
}
```
Also the SDK should export error types for each type of error, like ZapperError, this would allow us to also type which error_codes are accepted. (See https://medium.com/geekculture/how-to-strongly-type-try-catch-blocks-in-typescript-4681aff406b9 for more information about how to strong type errors from exceptions)
**Additional Context**
Screenshots, UI/UX designs, links or other that will help implementing the feature.

**Comment by edwinzhng** [comment]
If no one else is working on this, can I take this issue?

**Comment by xgambitox** [comment]
Sorry, issue was not closed. This was addressed in https://github.com/yearn/yearn-finance-v3/pull/468

Though there are still some errors that can be detailed better, we will create other issue when it gets documented properly.
