### ISSUE TITLE
[WEB-1331-476] WebApp whitescreens when depositing on FTM using CB Wallet

### ISSUE THREAD

**Issue by my-other-github-account** [yearn/yearn-finance-v3#476]
**Describe the bug**\
Deposits on YFI WebApp using Coinbase Wallet on iOS do not work when on the Fantom network.

ETH deposits work fine, and I can successfully see my FTM balances (DAI and CRV), as well as *supply* DAI, but once I hit the deposit button on either DAI or CRV the WebApp crashes and whitescreens until I refresh the page in Coinbase Wallet.

**To Reproduce**\

1. Go to [https://yearn.finance/#/wallet](https://yearn.finance/#/wallet) within the official Coinbase Wallet App on iOS
2. Select the Fantom network in the drop down at the top. You will be prompted to change CB Wallet to the Fantom network if you haven’t already.
3. Verify your balances of depositable currencies as correct for the FTM Opera chain
4. Click the deposit button next to one of these currencies

**Expected behavior**\
WebApp allows you to deposit the same way it works with ETH (ETH chain deposits are successful following these same steps)

**Environment Information**

* Device: iPhone 13 Pro
* OS: iOS 15.4
* Browser: Coinbase Wallet Browser
* Version Coinbase Wallet 25.7.552

**Comment by my-other-github-account** [comment]
To add, while I can deposit e.g. DAI to the DAI vault using the “vaults” page, the functionality to deposit e.g. from DAI to 3CRV is completely inaccessible currently as this is only possible AFAIK on the wallet page

**Comment by FoxTheSin** [comment]
> 

Right now we don't support "zaps" in Fantom. When you deposit into a fantom vault, it needs to be native token.
With Eth main net, on wallet page you can choose which vault. On vault page you can choose which token to deposit. As long as the vault supports zaps.

As for the whiteout issue from wallet page on fantom, it is being investigated!

Thank you for bug report. We appreciate.

**Comment by FoxTheSin** [comment]
tested and couldn't reproduce after updates. If this bug comes up again please create another issue.
