### ISSUE TITLE
[WEB-1356-484] feat: zap approval on withdraw

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#484]
**Elevator Pitch**\
When you withdraw to a different token, you need to approve a zap. Seem like wasted, improved by using permit there

**Customer Value**\
save 1 zap

**Definition of Done**\
customer doesn't have to approve zap on withdraw

**Design Approach**\
n/a

**Additional Context**\
[https://t.me/c/1152055703/21091](https://t.me/c/1152055703/21091)

**Comment by xgambitox** [comment]
feature added in #500
