### ISSUE TITLE
fix: yeild under modal displaying 0

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#493]
**Elevator Pitch**
When a new vault is created or introduced, no historical pricing is available. The Modal that presents "yield" % will show 0, should be listed as NEW (reflecting the vaults page)

**Customer Value**
Wont scare people with a 0% apy

**Definition of Done**
when website is loaded, the yield will display NEW (with the little star emoji)

**Design Approach**
Approach and considerations to build the task list / Existing code patterns in production code base that you will base your work off of.

**Additional Context**
Screenshots, UI/UX designs, links or other that will help implementing the feature.
![image](https://user-images.githubusercontent.com/79029523/155201204-374cf3c2-9929-48d1-8398-9ee80ff76457.png)

**Comment by karelianpie** [comment]
@FoxTheSin I was looking into this but unsure where is the modal that you're referring to, could you please let me know

**Comment by xgambitox** [comment]
In the particular case of yvBoost, it is due to an error in the APY calcs. We can display a hyphen '-' to distinguish those vaults with `apyMetadata.type === 'error'` so we can distinguish them.

**Comment by karelianpie** [comment]
> In the particular case of yvBoost, it is due to an error in the APY calcs. We can display a hyphen '-' on those vaults with `apyMetadata.type === 'error'` so we can distinguish them.

Sounds good to me. I'll add that to the `formatApy` util
