### ISSUE TITLE
fix: error warning about memory leak

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#494]
**Describe the bug**
After dom render, this error appears (see 1st screen shot below for specifics) "can't perform React state update on an unmounted component."

Possible problem: the img library to add opacity animation (see 2nd screen shot below)

Probably is trying to do some logic before the element is rendered/mounted

**To Reproduce**

**Expected behavior**
no errors should occur after render

**Screenshots**
1st screen, for error specifics
![d4f2ab67-565b-494b-9809-4e1bc0ac9ea0](https://user-images.githubusercontent.com/79029523/155347636-66fe9d6f-4a33-4678-8384-cb99070dd003.png)

possible investigation point
![1cc274d2-fdbf-4b67-b148-0087decaa5b4](https://user-images.githubusercontent.com/79029523/155347670-e6387d76-796e-4fa4-9939-56606260597b.png)

**Environment Information**

**Additional context**

**Comment by karelianpie** [comment]
@FoxTheSin looked at this but was unable to reproduce, could you please add the reproduction steps? 🙇

**Comment by FoxTheSin** [comment]
Closed until we can reproduce
