### ISSUE TITLE
feat: MetaMask add token button should add vault token

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#496]
**Elevator Pitch**
Currently, when you add token through the metamask button on vaults overview page it prompts for the token you are going to deposit, not the yVault token you recieve.

**Customer Value**
Will show the vault token in wallet after deposit, which may assure the user "funds are safu"
Whatever token they are depositing should already be in their wallet.

**Definition of Done**
Upon clicking MM add button on anywhere should add the vault token.

**Design Approach**

**Additional Context**
These metamask buttons, wherever they are found (vaults and labs)
![Screen Shot 2022-02-23 at 7 27 56 AM](https://user-images.githubusercontent.com/79029523/155351014-9584686b-a217-449e-867a-ab622c875e53.png)

This should be the ySushi token
<img width="436" alt="Screen Shot 2022-02-23 at 7 28 20 AM" src="https://user-images.githubusercontent.com/79029523/155351110-bba2e3a3-2253-49ab-bfee-c3e5e54e1c46.png">

**Comment by FoxTheSin** [comment]
> You have to synchronize your wallet and debug it

This has nothing to do with the wallet. We're looking to update the buttons on the webpage.

**Comment by karelianpie** [comment]
Created the PR https://github.com/yearn/yearn-finance-v3/pull/517 to address this issue, it might require changes, but it will have the ball rolling to solve this
