### ISSUE TITLE
fix: exit button after deposit/withdraw from Vault Details View refactor

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#505]
**Elevator Pitch**
The exit button in the vault details transaction, should be DONE not EXIT.

This button appears after a successful transaction in the vault details.

In the modals, the button is ok and should be keep like that.

The ideal solution would be to send to the tx component, a prop with the endTransactionButtonActionType or something like that, as endTransactionButtonActionType: 'exit' | 'done' .

In the modal, the exit button should close the modal (this works fine).

In the vault details, the done button it should just reset it.

**Customer Value**
The tx modal stuck in vault details after a successful tx doesn't look good, 

**Definition of Done**
-After a tx, the modal resets

**Design Approach**

**Additional Context**
https://linear.app/yearn/issue/WEB-851/exit-button-after-depositwithdraw-from-vault-detail-view-refactor

**Comment by gotzenx** [comment]
Gonna close this since @turtlemoji has a PR for it
