### ISSUE TITLE
fix: vault details page approve button

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#507]
**Describe the bug**
When user loads the website directly on Vaults Detail View, fetching of token allowance is being made before the wallet is connect. This results in the fetch throwing an error so the app never gets the user allowance correctly. This is the reason why we will always display the `Approve` token button as enabled since logic doesnt have the allowance value.

**To Reproduce**
1. Identify a vault that you know you have approve the underlying token to deposit.
2. Navigate to that vaults detail view by clicking on it from the vaults list.
3. Once inside the Detail View, refresh the web
Note: on redux dev tools you will find that the action `getTokenAllowance` got rejected with error: WALLET NOT CONNECTED.
You should use the dev build that has redux logging enabled: https://develop.d27dgpz01hmbvx.amplifyapp.com/#/vaults

**Expected behavior**
- We should fetch `getTokenAllowance` successfully after wallet is connected. 
- Approve button should be displayed as disabled and `deposit` button enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/78360669/156790227-22ebb758-7ade-42d7-a156-a313dc0efe49.png)
![image](https://user-images.githubusercontent.com/78360669/156790368-c7da8b10-2020-4292-970f-f90292cd2b56.png)
Note: on the second image we can see that we are dispatching getTokenAllowace before walletChange action

**Environment Information**

**Additional context**

**Comment by phillip055** [comment]
Picking up this one, if no one has yet

**Comment by FoxTheSin** [comment]
> Picking up this one, if no one has yet

hey Phillip! At our cycle planning today this issue cropped up as being important. Any chance you have time to work on it in the next day?

**Comment by phillip055** [comment]
Hey yes sure, starting to work on it right away

**Comment by FoxTheSin** [comment]
> Hey yes sure, starting to work on it right away

Thanks! Holler in the telegram group if you have any questions.
