### ISSUE TITLE
feat: create a test build for PR

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#521]
**Elevator Pitch**
While investigating a quick fix error, we noticed two previous releases weren't published. We'd like a github action to test for lint error and test a build for PR's

deploy failed since we cant see our recent changes in prod, need to have an alert so we can notice if this happens again

Github action to check for lint error 

**Customer Value**
Benefits that will be achieved.

**Definition of Done**
Github action checks build doesnt fail after every push in a PR

**Design Approach**
Approach and considerations to build the task list / Existing code patterns in production code base that you will base your work off of.

**Additional Context**
Screenshots, UI/UX designs, links or other that will help implementing the feature.

**Comment by FoxTheSin** [comment]
a github action should at least run a build

**Comment by turtlemoji** [comment]
I could to it after revamp. @FoxTheSin

**Comment by turtlemoji** [comment]
done in #580
