### ISSUE TITLE
fix: vault details performance card 

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#523]
**Describe the bug**
If there is only 1 data point for "perfomance" in the vault details page, it provides no details and just shows a single dot on a blank grid.

**To Reproduce**
1. Go to yearn.finance/vaults

2. Click on Curve alETh, Curve EURT, or Curve TUSD

3. performance card should only show the 1 data point with no context or grid.

**Expected behavior**
When a single harvest/data point is available, don't display graph. Only "earnings over time" amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/79029523/157564206-4da7b8c8-f27c-430c-86f0-152d109cb474.png)

vs 

![image](https://user-images.githubusercontent.com/79029523/157564233-e11d0c4b-f020-4c62-a9ac-1ba88b434ef5.png)

**Environment Information**

**Additional context**

**Comment by edwinzhng** [comment]
Working on this
