### ISSUE TITLE
fix: vaults from the labs page do not read overrides from yearn-meta

### ISSUE THREAD

**Issue by jstashh** [yearn/yearn-finance-v3#524]
**Describe the bug**
yvBoost apy is overriden in meta - https://github.com/yearn/yearn-meta/blob/master/data/vaults/1/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a.json

however it's not being used for displaying the apy %

<img width="524" alt="Screenshot 2022-03-10 at 12 55 40" src="https://user-images.githubusercontent.com/19509999/157666200-174202ea-311a-4cd9-b56c-ea44624da0ec.png">

**To Reproduce**
1. Go to labs screen
2. View yvboost

**Expected behavior**
Data is read from yearn meta so that apys are overriden if necessary

**Environment Information**
 - Web/Brave

**Comment by edwinzhng** [comment]
Working on this

**Comment by karelianpie** [comment]
Was looking into this as I want to gain a little bit more understanding about yearn-meta. Had a go with the following PRs

* https://github.com/yearn/yearn-finance-v3/pull/558
* https://github.com/yearn/yearn-sdk/pull/263

Keen to know if there is a better way
