### ISSUE TITLE
fix: rainbow - wallet connect mobile

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#532]
**Describe the bug**
Rainbow wallet on mobile isn't playing well with yearn.finance

**To Reproduce**
1. On a mobile device (potentially on desktop as well?) connect to yearn.finance
2. Connect a Rainbow wallet
3. open a transaction modal (depsoit or withdraw)
4. doesn't work

**Expected behavior**
Should be able to conduct transactions with rainbow wallet on mobile

**Screenshots**
![image](https://user-images.githubusercontent.com/79029523/158037760-a333592d-99d2-4ea6-9c52-cc61d39c213e.png)

**Environment Information**

**Additional context**

**Comment by pentcle** [comment]
steps taken having cleared safari cache on ios


go to yearn.finance

![image0](https://user-images.githubusercontent.com/80323528/158038452-ac8f9abb-04db-462b-b49f-49f46fc57dd4.png)


tap to connect wallet

![image1](https://user-images.githubusercontent.com/80323528/158038451-d013f7cd-fa6c-46ce-a04e-97ea3e337a5f.png)


tap rainbow

![image2](https://user-images.githubusercontent.com/80323528/158038449-55688fb9-115e-4a67-8175-2fdab2c9f1e2.png)


tap to connect

![image3](https://user-images.githubusercontent.com/80323528/158038448-e8cf54e8-2339-447e-9ab1-de76bf44a04a.png)


why am i now at the app store? 

![image4](https://user-images.githubusercontent.com/80323528/158038446-2f147dc3-97a0-459a-9d84-d8ea157f85a1.png)


open rainbow wallet app on phone (was hazarding a guess to try that)

![image5](https://user-images.githubusercontent.com/80323528/158038444-493ac316-dce2-430d-974f-4de52307f7e1.png)


return to yearn.finance, my wallet is connected

![image0](https://user-images.githubusercontent.com/80323528/158038569-ab101b77-bbca-4f4b-bb4a-b408bcb5b6c2.png)

**Comment by pentcle** [comment]
step ii - am now connected via rainbow wallet

tap to deposit ETH
 
![image1](https://user-images.githubusercontent.com/80323528/158039027-15af5121-06e3-45ea-9e40-2b8e4d367eec.png)

ignore warning message and tap to deposit max

![image0 (1)](https://user-images.githubusercontent.com/80323528/158039041-25fed5cc-9e6a-44f5-a3ed-c59b005f8cbd.png)

tap approve button
- nothing happens

tap deposit button
 -nothing happens

**Comment by banteg** [comment]
related
https://github.com/blocknative/web3-onboard/issues/808
https://github.com/blocknative/web3-onboard/issues/764
