### ISSUE TITLE
fix: $0 TVL incorrect

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#535]
**Describe the bug**
The vault Curve YFI-ETH is currently displaying as $0 despite having holders of the token. 

**To Reproduce**
Steps to reproduce the behavior (for yfi-eth)
1. [yearn.finance](https://yearn.finance/#/vault/0x790a60024bC3aea28385b60480f15a0771f26D09)
2. Navigate to ethereum network
3. go to vaults, scroll down to yfi-eth

4. see $0 total asset

5. go to etherscan, then token tracker

6. https://etherscan.io/token/0x790a60024bC3aea28385b60480f15a0771f26D09

there are users with funds in vault

**Expected behavior**
If there are funds in the vault, that TVL should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/79029523/158207547-456972bd-78e6-42b9-9143-6cef3af1a029.png)

**Environment Information**

**Additional context**

**Comment by nuggetnchill** [comment]
It shows up now

<img width="547" alt="image" src="https://user-images.githubusercontent.com/65918030/161126110-c63d2b3e-aadc-40e0-a6f5-bf0a31c7d8f4.png">

maybe it wasn't the FE

**Comment by FoxTheSin** [comment]
yup! fixed.
