### ISSUE TITLE
feat: vault details page for all Lab vaults

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#538]
**Elevator Pitch**
We need a vault details page specifically for labs.

**Customer Value**
Customers would be able to see the contract link and get a better idea of what the heck veCRV , yvboost, and teh pickle jar is all about.

**Definition of Done**
When clicked either in the "Highest APY" card or "opportunities" card, should link to the Vault Details Page

**Design Approach**
Approach and considerations to build the task list / Existing code patterns in production code base that you will base your work off of.

**Additional Context**
![image](https://user-images.githubusercontent.com/79029523/158248565-f980f768-1688-4e78-be4c-e9bc20271447.png)

![image](https://user-images.githubusercontent.com/79029523/158248639-c2ab0792-d1e1-455d-a294-2195cd65fa54.png)

**Comment by DarkGhost7** [comment]
This is helpful because at times I go to the website to find the vault contract by click on the name of the vault, I believe if it doesnt have a vault detail page I cannot find the vault contract for that vault from the website.

**Comment by karelianpie** [comment]
Created a PR for this issue, https://github.com/yearn/yearn-finance-v3/pull/561
