### ISSUE TITLE
fix: APY for curve rocket messes up UI

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#548]
**Describe the bug**

**To Reproduce**
1. go to yearn.finance
2. navigate to vaults tab
3. Highest APY ui is broken
4. go into curve rocket "vault details"
5. ui is messy there as well

**Expected behavior**
UI should not be broken by APY

**Screenshots**

**Environment Information**

**Additional context**
<img width="891" alt="image" src="https://user-images.githubusercontent.com/79029523/159099115-e7f357cf-be2b-4630-9aee-ef0ccbb886b7.png">

<img width="699" alt="image" src="https://user-images.githubusercontent.com/79029523/159099152-a1c47651-d446-4bd7-acd1-cfcdeb5ee62d.png">

**Comment by mw2000** [comment]
Should close this issue
