### ISSUE TITLE
feat: add link to blog on yearn.finance in footer

### ISSUE THREAD

**Issue by djgano** [yearn/yearn-finance-v3#564]
**Elevator Pitch**
Add a link to the blog in the footer of the main page at https://yearn.finance

**Customer Value**
This will expose more users  to the blog and help them stay more informed about news and updates.

**Definition of Done**
- The link is displayed in the footer.
- Clicking the link takes the user to https://blog.yearn.finance/

**Design Approach**
- The distance between footer links is closer than before (see images below).
- The layout should adjust properly for mobile sizes. Notice currently there are 3 diff layout styles as the page width reduces.
- Font face, size, and color should match the other footer links.

**Additional Context**
![image](https://user-images.githubusercontent.com/102051251/160447621-7a4fcb84-0624-4283-8a3e-4416b28e0d4a.png)

![image](https://user-images.githubusercontent.com/102051251/160446345-3f1d2537-1f9d-46c2-94e1-7ade20ebe46e.png)

![image](https://user-images.githubusercontent.com/102051251/160446829-a728363c-f965-4317-8018-60f4864c10fc.png)

**Comment by nuggetnchill** [comment]
I'll work on this

**Comment by FoxTheSin** [comment]
merged <3
