### ISSUE TITLE
feat: Shared Components for both lab's and vault's details view

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#570]
**Elevator Pitch**
For future details pages, we should have shared components between labs and vaults to easily create details page

**Customer Value**
a consistent users experience across the site

**Definition of Done**
labs and vaults both share components

**Design Approach**
Approach and considerations to build the task list / Existing code patterns in production code base that you will base your work off of.

**Additional Context**

[github PR that should help with context](https://github.com/yearn/yearn-finance-v3/pull/561)

**Comment by nuggetnchill** [comment]
do we have to wait for that PR to merge first before working on this?

**Comment by xgambitox** [comment]
> do we have to wait for that PR to merge first before working on this?

Yes, we should probably wait for [this PR](https://github.com/yearn/yearn-finance-v3/pull/561) to be finished first, since we dont want to generate conflicts with anyone taking this one.
