### ISSUE TITLE
fix: unhandled error message on vault pages

### ISSUE THREAD

**Issue by djgano** [yearn/yearn-finance-v3#600]
**Describe the bug**
With no wallet connected...
there's a yellow-orange non-human-readable warning message displayed in the Deposit section of the vault.

**To Reproduce**
1. Go to yearn.finance with no wallet connected.
2. Click on Vaults
3. Click on any vault such as Curve Rocket Pool
4. Notice the big yellow-orange box on the right.

**Expected behavior**
A helpful, human readable message is displayed such as "please connect your wallet".

**Screenshots**
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/102051251/163838345-6f42f7d3-cc5c-4016-bd79-d7ed40bf993e.png">

**Environment Information**
 - Device: desktop
 - OS: Big Sur 11.5.2
 - Browser: Chrome
 - Version: 100.0.4896.88

**Additional context**
This is the text within the warning:

AT HTTPS://YEARN.FINANCE/STATIC/JS/22.9BFB98DF.CHUNK.JS:2:59884\N AT SE.OBJECT.ASSIGN.PENDING (HTTPS://YEARN.FINANCE/STATIC/JS/22.9BFB98DF.CHUNK.JS:2:60432)\N AT HTTPS://YEARN.FINANCE/STATIC/JS/22.9BFB98DF.CHUNK.JS:2:53208\N AT HTTPS://YEARN.FINANCE/STATIC/JS/MAIN.CED0CAFC.CHUNK.JS:8:132603\N AT HTTPS://YEARN.FINANCE/STATIC/JS/MAIN.CED0CAFC.CHUNK.JS:8:132780\N AT JU (HTTPS://YEARN.FINANCE/STATIC/JS/22.9BFB98DF.CHUNK.JS:2:1858344)\N AT T.UNSTABLE_RUNWITHPRIORITY (HTTPS://YEARN.FINANCE/STATIC/JS/22.9BFB98DF.CHUNK.JS:2:1876155)"}

**Comment by FoxTheSin** [comment]
potential fix coming from https://github.com/yearn/yearn-finance-v3/pull/586

**Comment by djgano** [comment]
Just a heads-up that this appears to still be an issue. I understand if it's deemed a lower priority to other tickets.

I also noted #586 was closed it favor of #584.
