### ISSUE TITLE
accessibility: inputs have name, id, label

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#602]
**Elevator Pitch**
Each input should have a name, and ID, and a label

**Definition of Done**
Each input should have a name, and ID, and a label

**Design Approach**
[All form inputs have explicit labels](https://accessibility.18f.gov/forms/)
Checklist item A-3 from uk accessibility standards

**Additional Context**
please check with @pentcle and/or @turtlemoji for additional UI details

**Comment by trezi29** [comment]
Working on this

**Comment by FoxTheSin** [comment]
Thanks @trezi29 , more to come!
