### ISSUE TITLE
fix: portfolio wallet deposit modal

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#626]
**Describe the bug**
From the portfolio page, cannot change which vault depositing into

**To Reproduce**
1. Go to portfolio page
2. Click on deposit from any token in wallet

**Expected behavior**
Should be able to change which vault being deposited or zapped into

**Screenshots**
wbtc can only go to wbtc from wallet 
![image](https://user-images.githubusercontent.com/79029523/166518655-0a71d117-01d1-4ae7-a98c-e6317373cc4d.png)

but from other vaults I can deposit wbtc

CRV is only pointing to rocket (like many other vaults, rocket is default)
![image](https://user-images.githubusercontent.com/79029523/166518699-80fb687e-1b13-486c-8c4b-1ba5361ba0ce.png)

but from vault details on other vaults I can zap.

**Environment Information**

**Additional context**

**Comment by edwinzhng** [comment]
I can look into this
