### ISSUE TITLE
fix: deposit to pickle

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#627]
**Describe the bug**
when in deposit modal (for pickle jar) it isn't recognizing yvBOOST balance

**To Reproduce**
1. Go to labs
2. select deposit
3. select yvBOOST as deposit token

**Expected behavior**
Should be able to zap in yvBOOST from deposit modal

**Screenshots**
0 balance listed when balance is available to deposit.
![image](https://user-images.githubusercontent.com/79029523/166521460-49d2a91f-1d14-4f42-83e6-8d8f9486a680.png)

**Environment Information**

**Additional context**

**Comment by edwinzhng** [comment]
I can look into this as well
