### ISSUE TITLE
feat: toggle switch for 0 APY

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#659]
**Elevator Pitch**
add a toggle switch to control when 0% APY vaults are displayed

**Customer Value**
Users, by default, shouldn't see 0 apy vaults

**Definition of Done**

- toggle switch labeled "hide %0 APY vaults"
- displayed in vaults/opportunities for all chains
- on by default (hiding 0 apy vaults)

**Design Approach**
please put switch here
There should be a switch
![image](https://user-images.githubusercontent.com/79029523/168114185-39c250bf-f462-41a7-b265-f0baa0694812.png)

similar to the "dust" of wallets
![image](https://user-images.githubusercontent.com/79029523/168115061-3a51c410-deec-4ae7-8f56-afeb09f6b3e2.png)

**Additional Context**
Screenshots, UI/UX designs, links or other that will help implementing the feature.

**Comment by FoxTheSin** [comment]
find logic created in this PR
https://github.com/yearn/yearn-finance-v3/pull/656

**Comment by edwinzhng** [comment]
I can take this :D

**Comment by edwinzhng** [comment]
In that case, maybe just "Show 0% APY" to be precise?

**Comment by xgambitox** [comment]
> In that case, maybe just "Show 0% APY" to be precise?

cool, lets go with that one :)
