### ISSUE TITLE
having problems with dev environment setup

### ISSUE THREAD

**Issue by maraoz** [yearn/yearn-finance-v3#671]
Hi! I'm following the README's guide for project setup, and I'm stuck with the https://github.com/yearn/yearn-finance-v3#yearnweb-lib-access section. 

I've created the Github Personal Access Token as described in the guide, but I'm getting
```
error An unexpected error occurred: "https://npm.pkg.github.com/download/@yearn/web-lib/0.2.27/a5aec6437505213aef6fb84cf564053246dd21b7cb0105c33c517bfe872ed3bc: Request failed \"401 Unauthorized\"".
```
every time I run `yarn install` -- no matter what premissions I assign to the token. 

Two questions:
1) what permissions are required for the gh personal access token for `yarn install` and `yarn dev` to work?
2) does someone from yearn need to give me read acces to `@yearn/web-lib`, or is this a misconfiguration on my end? 

Thanks in advance!

**Comment by maraoz** [comment]
I should clarify that when I run `npm config get npm.pkg.github.com/:_authToken`, I see my personal access token printed in my shell, so I seem to have configured the `.npmrc` correctly

**Comment by xgambitox** [comment]
Hey there @maraoz ! sorry readme is not clear enough, this web-lib dependency was introduced recently. Please follow this [instructions](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token).

The permissions needed in the personal access token are described [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token)

If you are able to set it up properly, please feel free to update the README :)

**Comment by maraoz** [comment]
thanks @xgambitox ! I had just fixed it myself by including the access token config in the `.npmrc` for this repo (not the global one). I'll update README next. thanks!

**Comment by xgambitox** [comment]
@maraoz just be aware that by including the PAT in the file inside the repo rather in the global home directory, there is a high risk of pushing the token to the public repo in github, which is not ideal.
