### ISSUE TITLE
Error: space needed

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-finance-v3#675]
**Describe the bug**
![image](https://user-images.githubusercontent.com/38810205/168672462-7806f8a2-c8e5-4f30-bbd2-332693f93cdd.png)

**To Reproduce**
1. Go to https://yearn.finance/#/vaults
2. search for something not listed
3. See error

**Expected behavior**
Should say No assets to display. Please search for another asset

**Comment by turtlemoji** [comment]
Already fixed on develop
